name: Generate Certificate

on:
  push:
    branches:
      - master

jobs:
  generate_certificate:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run PowerShell script
        shell: pwsh
        run: |
          # Generate the certificate using PowerShell
          $certificate = New-SelfSignedCertificate -Type Custom -Subject "CN=MyCompany, O=MyCompany, L=MyCity, S=MyState, C=MyCountry" -KeyUsage DigitalSignature -FriendlyName "UWPApp Certificate" -CertStoreLocation "Cert:\CurrentUser\My" -TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.3", "2.5.29.19={text}")

          # Get the thumbprint of the generated certificate
          $thumbprint = $certificate.Thumbprint

          # Output the thumbprint
          Write-Output "CERTIFICATE_SHA=$thumbprint"
