name: UWP Application Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1  # Use version 4.1.1 of actions/checkout

      - name: Download and Install Windows SDK
        run: |
          # Download Windows SDK installer
          Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/?linkid=2261842" -OutFile "windows-sdk-setup.exe"

          # Execute Windows SDK installer
          .\windows-sdk-setup.exe /quiet /installpath C:\Windows Kits\10

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2.2.0

      - name: Install MSYS2 packages
        run: |
          # Install necessary packages using pacman
          pacman -S --noconfirm mingw-w64-x86_64-gcc mingw-w64-x86_64-make

      - name: Build UWP application
        run: |
          # Navigate to your project directory
          cd $GITHUB_WORKSPACE
          # Run make to build the application
          make
          # Run make to package the application
          make package

      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: uwp_application
          path: UWPApp.msix 
