name: UWP Application Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1  

      - name: Setup Windows 10 SDK Action
        uses: GuillaumeFalourd/setup-windows10-sdk-action@v2 

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2.22.0

      - name: Fetch Dependencies
        run: |
          pacman -S --noconfirm unzip make git mingw-w64-x86_64-gcc mingw-w64-x86_64-make python3
     
      - name: Generate Certificate
        shell: pwsh
        run: |
          # Generate the certificate using PowerShell
          $certificate = New-SelfSignedCertificate -Type Custom -Subject "CN=MyCompany, O=MyCompany, L=MyCity, S=MyState, C=MyCountry" -KeyUsage DigitalSignature -FriendlyName "UWPApp Certificate" -CertStoreLocation "Cert:\CurrentUser\My" -TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.3", "2.5.29.19={text}")

          # Export the certificate to a file
          $certificatePath = Join-Path -Path $env:TEMP -ChildPath "uwp_certificate.pfx"
          Export-PfxCertificate -Cert $certificate -FilePath $certificatePath -Password (ConvertTo-SecureString -String "password" -AsPlainText -Force)

          # Output the path to the exported certificate
          Write-Output "CERTIFICATE_PATH=$certificatePath"

      - name: Build UWP application
        run: |
          # Navigate to your project directory
          cd $GITHUB_WORKSPACE
          # Run make to build the application
          make
          # Run make to package the application
          make package

      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: uwp_application
          path: UWPApp.msix
